### PR TITLE
Use local app data directory for ini file on Windows

### PR DESCRIPTION
**Pull request by coldacid**
Stop putting BiblioteQ.ini in a potentially unwritable location on Windows (i.e. in a subdirectory of where the application is installed). Instead, put the file in a BiblioteQ directory in the user's local app data directory, which should always be writable for the user.

### CODE REVIEW

**Comment by textbrowser** [comment]
Sure, will stop!

**Comment by textbrowser** [comment]
Wait! BQ should be launched from wherever the executable is. The AppConfigLocation may be different than the current path. If the BQ folder is removed, there will be lingering file(s).

**Comment by textbrowser** [comment]
That'll make portable people unhappy.

**Comment by coldacid** [comment]
If a command line option is added for portable use that continues to look in the install directory, then such users can be accommodated. However portable installs should be considered the non-standard way of using an application on Windows, especially as applications are usually installed in locations which are not writable by standard users.

**Comment by textbrowser** [comment]
BQ is not meant to be installed on Windows. Who is installing it? How? Where? Why?

**Comment by textbrowser** [comment]
And Windows people do not expect command-line options. Click-and-launch.

**Comment by textbrowser** [comment]
Can we set this if some value is set in the project file? Like, if you're building BQ for a special process. Maybe if a specific directory or file exists on that system.

**Comment by textbrowser** [comment]
Please append the variable BIBLIOTEQ_NON_PORTABLE to DEFINES in biblioteq.win.pro.

**Pull request merged**
