### PR TITLE
Convert mainWindow slots to QML

### PR DESCRIPTION
**Pull request by jgiszczak**
Remove manually written boilerplate code in favor of machine-generated boilerplate code.

### CODE REVIEW

**Comment by textbrowser** [comment]
Many changes. :) Did you test them?

**Comment by jgiszczak** [comment]
Many changes but all of a kind.  I tested most of them, including all menu and toolbar actions, but do please inspect the diff carefully to be sure I didn't misspell any slot names.  The one downside of this method is the late binding it does which lacks compiler checks of method names.  I caught one misspelling during testing.  I'm fairly sure there are no more, but a second look is advisable.

**Comment by textbrowser** [comment]
> Many changes but all of a kind. I tested most of them, including all menu and toolbar actions, but do please inspect the diff carefully to be sure I didn't misspell any slot names. The one downside of this method is the late binding it does which lacks compiler checks of method names. I caught one misspelling during testing. I'm fairly sure there are no more, but a second look is advisable.

Was the misspelling which you discovered a misspelling of the conversion or of existing source?

**Comment by jgiszczak** [comment]
It was my error during conversion.

Having three variants in the slot naming scheme made things a little more difficult...

**Comment by textbrowser** [comment]
Please connect() according to https://wiki.qt.io/New_Signal_Slot_Syntax. The new method will capture errors during compilation.

However, in Qt 5.5.1, this is not necessarily simple with parameterized methods. For those, the traditional connect() will suffice.

**Pull request closed without merging**
