### PR TITLE
Translation French version 2023-05-06.

### PR DESCRIPTION
**Pull request by meteos77**
This is my 1st commit, I hope all is good.
Thanks for the integration.

### CODE REVIEW

**Comment by textbrowser** [comment]
Thanks.

**Comment by meteos77** [comment]
Sorry I made a mistake in the docs copy directory.

**Comment by textbrowser** [comment]
Oh yes I see now. Well, that's your fault.

**Comment by textbrowser** [comment]
Yah, lots of littered files everywhere.

**Comment by textbrowser** [comment]
And it's my fault for trusting people. :)

**Comment by meteos77** [comment]
especially for a first :-)

next time I understood, all in the right place and you validate with your eyes closed.

**Comment by meteos77** [comment]
If I make a fork, can I release the .deb and exe versions in my directory too?

**Comment by textbrowser** [comment]
You can do anything with a fork. It's independent of my repository. If you make a pull request with this repository, I can accept or decline it.

**Pull request merged**
